import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserContextProvider } from "./_context/User";
import { PostContextProvider } from "./_context/Post";
import Provider from "./Provider";
import { GoogleOAuthProvider } from "@react-oauth/google";

// export const metadata = {
//   title: "Home",
//   description: "Generated by Rajat jain",
// };

const googleAuth = {
  clientID:
    "395554230435-mnj4fjp3m9itagnm1etd160m1c62nkkp.apps.googleusercontent.com",
  ClientSecret: "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",
  api: "https://www.googleapis.com/oauth2v3/userinfo",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className=''>
      <body>
        <GoogleOAuthProvider clientId={googleAuth.clientID}>
          <UserContextProvider>
            <PostContextProvider>
              <Provider>{children}</Provider>
              <Toaster position='bottom-center' reverseOrder={false} />
            </PostContextProvider>
          </UserContextProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
